version: 2

jobs:
  build-linux:
    docker:
      - image: "gcc:7"
    steps:
      - checkout
      - run:
          name: install sudo
          command: 'apt-get update && apt-get install -y sudo'
      - run:
          name: install cmake
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: update submodule
          command: 'git submodule update --init'
      - run:
          name: generate build config
          command: 'cmake -H. -B_build'
      - run:
          name: build project
          command: 'cmake --build _build'
      - run:
          name: test
          command: './_build/bin/tests'
      - run:
          name: install prerequisite for coverage
          command: 'apt-get update && apt-get install -y lcov curl'
      - run:
          name: generate coverage config
          command: 'cmake -H. -B_coverage -DCMAKE_BUILD_TYPE=Debug -DLCOV_COVERAGE=On'
      - run:
          name: build coverage
          command: 'cmake --build _coverage -- starter-template_coverage'
      - run:
          name: codecov
          command: 'curl -s https://codecov.io/bash | bash'

workflows:
  version: 2
  build-test:
    jobs:
      - build-linux