version: 2

jobs:
  build-linux:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -B_build'
      - run:
          name: Creating Binary Files
          command: 'cmake --build _build'
      - run:
          name: Point Unit Testing
          command: './bin/tests'